# Generated by Django 6.0.2 on 2026-02-13 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_vendor_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendor",
            name="country",
            field=models.CharField(default="United States", max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="internal_rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="represented_vendors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vendor",
            name="relationship_start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vendor",
            name="stock_symbol",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_spend",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                choices=[
                    ("wholesaler", "Wholesaler"),
                    ("manufacturer", "Manufacturer"),
                    ("distributor", "Distributor"),
                ],
                default="wholesaler",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
