# Generated by Django 6.0.2 on 2026-02-13 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_vendor_contact_email_vendor_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="relationship_start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
