# Generated by Django 6.0.2 on 2026-02-20 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_vendor_relationship_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="risk_tier",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_id", models.CharField(max_length=100)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False, editable=False)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="management.vendor",
                    ),
                ),
            ],
        ),
    ]
