# Generated by Django 5.2.11 on 2026-02-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_contract_model_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contract',
            new_name='management__start_d_c0b5ff_idx',
            old_name='management_c_start_d_388d81_idx',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='risk_tier',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='medium', max_length=20),
        ),
    ]
