# Generated by Django 5.2.11 on 2026-02-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0007_rename_management_c_start_d_388d81_idx_management__start_d_c0b5ff_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="notified_15_days",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certification",
            name="notified_1_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certification",
            name="notified_30_days",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certification",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="risk_tier",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("verified", "Verified"),
                    ("inactive", "Inactive"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
